# Generated by Django 3.1.5 on 2022-05-12 13:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(default='', max_length=32)),
                ('is_passive', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GoodslinesSummable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HotTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='_', max_length=128)),
                ('name_id', models.CharField(default='_', max_length=128)),
                ('has_goodslines', models.SmallIntegerField(default=0)),
                ('is_employees_action', models.IntegerField(default=0)),
                ('cred_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hot_transaction_cred', to='pages.bookaccount')),
                ('deb_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hot_transaction_deb', to='pages.bookaccount')),
            ],
        ),
        migrations.CreateModel(
            name='HumanId',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('created_by', models.ForeignKey(default=376, on_delete=django.db.models.deletion.CASCADE, related_name='partner_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='_', max_length=50)),
                ('name_id', models.CharField(default='_', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('has_goodslines', models.SmallIntegerField(default=0)),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('created_by', models.ForeignKey(default=376, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_created_by', to=settings.AUTH_USER_MODEL)),
                ('cred_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_creds', to='pages.bookaccount')),
                ('deb_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_debs', to='pages.bookaccount')),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_employee', to='pages.partner')),
                ('hot_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_hot_transactions', to='pages.hottransaction')),
                ('human_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_human_id', to='pages.humanid')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_partner', to='pages.partner')),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_group',
            field=models.ForeignKey(default=879311, on_delete=django.db.models.deletion.CASCADE, related_name='partner_group', to='pages.partnergroup'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('created_by', models.ForeignKey(default=376, on_delete=django.db.models.deletion.CASCADE, related_name='material_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KilledTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('has_goodslines', models.SmallIntegerField(default=0)),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('kill_date', models.DateTimeField(default='1970-01-01')),
                ('created_by', models.ForeignKey(default=376, on_delete=django.db.models.deletion.CASCADE, related_name='killed_transaction_created_by', to=settings.AUTH_USER_MODEL)),
                ('cred_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killed_transaction_creds', to='pages.bookaccount')),
                ('deb_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killed_transaction_debs', to='pages.bookaccount')),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='killed_transaction_employee', to='pages.partner')),
                ('hot_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_transaction_hot_transactions', to='pages.hottransaction')),
                ('human_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_transaction_human_id', to='pages.humanid')),
                ('killed_by', models.ForeignKey(default=376, on_delete=django.db.models.deletion.CASCADE, related_name='killed_transaction_killed_by', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killed_transaction_partner', to='pages.partner')),
            ],
        ),
        migrations.CreateModel(
            name='KilledGoodsline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_human_id', models.CharField(blank=True, default='', max_length=32)),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ship_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ship_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('kill_date', models.DateTimeField(default='1970-01-01')),
                ('created_by', models.ForeignKey(default=376, on_delete=django.db.models.deletion.CASCADE, related_name='killed_goodsline_created_by', to=settings.AUTH_USER_MODEL)),
                ('human_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_goodsline_human_id', to='pages.humanid')),
                ('killed_by', models.ForeignKey(default=376, on_delete=django.db.models.deletion.CASCADE, related_name='killed_goodsline_killed_by', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='killed_goodsline_material', to='pages.material')),
                ('root_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_goodsline_root_transaction', to='pages.killedtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Goodsline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_human_id', models.CharField(blank=True, default='', max_length=32)),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('ship_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ship_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('created_by', models.ForeignKey(default=376, on_delete=django.db.models.deletion.CASCADE, related_name='goodsline_created_by', to=settings.AUTH_USER_MODEL)),
                ('human_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodsline_human_id', to='pages.humanid')),
                ('material', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goodsline_material', to='pages.material')),
                ('root_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodsline_root_transaction', to='pages.transaction')),
            ],
        ),
    ]
