# Generated by Django 3.1.5 on 2022-05-15 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsline',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goodsline_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='killedgoodsline',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='killed_goodsline_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='killedgoodsline',
            name='killed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='killed_goodsline_killed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='killedtransaction',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='killed_transaction_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='killedtransaction',
            name='killed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='killed_transaction_killed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='material_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partner_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partner_group', to='pages.partnergroup'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
