from django.urls import path
from django.http import HttpResponse
from django.views.decorators.cache import never_cache

try:
    from .views import *
    
    urlpatterns = [
        path('', 
            never_cache(
                MainPage.as_view()
            ), 
            name = 'mainpage'   # for login
        ), 
        path('tabs/show_frame/', 
            never_cache(
                ShownFrame.as_view() 
            )
        ),
        path('tabs/show_header/', 
            never_cache(
                ShownHeader.as_view() 
            )
        ),
        # shown 'table' parts of tabs 
        # various pivot tables first
        path('tabs/show/pivot/partner/', 
            never_cache(
                ShownPivotPartner.as_view() 
            )
        ),
        path('tabs/show/pivot/material/', 
            never_cache(
                ShownPivotMaterial.as_view() 
            )
        ),
        path('tabs/show/pivot/transaction/', 
            never_cache(
                ShownPivotTransaction.as_view() 
            )
        ),
        path('tabs/show/pivot/killed_transaction/', 
            never_cache(
                ShownPivotKilledTransaction.as_view() 
            )
        ),
        path('tabs/show/pivot/goodsline/', 
            never_cache(
                ShownPivotGoodsline.as_view() 
            )
        ),
        path('tabs/show/material_history/goodsline/', 
            never_cache(
                ShownMaterialHistoryGoodsline.as_view() 
            )
        ),
        path('tabs/show/inventories/goodsline/', 
            never_cache(
                ShownInventoriesGoodsline.as_view() 
            )
        ),
        path('tabs/show/in_stock/goodsline/', 
            never_cache(
                ShownInStockGoodsline.as_view() 
            )
        ),
        path('tabs/show/pivot/killed_goodsline/', 
            never_cache(
                ShownPivotKilledGoodsline.as_view() 
            )
        ),
        path('tabs/show/acc_sum_card/transaction/', 
            never_cache(
                ShownPivotAccSumCard.as_view()
            )
        ),
        path('tabs/show/partners_balance/partner/', 
            never_cache(
                ShownPartnersBalancePartner.as_view()
            )
        ),
        path('tabs/show/partners_balance/transaction/', 
            never_cache(
                ShownPartnersBalanceTransaction.as_view() 
            )
        ),
        path('tabs/show/trial_balance/book_account/', 
            never_cache(
                ShownTrialBalanceBookAccount.as_view() 
            )
        ),
        # tables with forms to edit vals
        path('tabs/show/edit/partner/', 
            never_cache(
                ShownEditPartner.as_view() 
            )
        ),
        path('tabs/show/edit/material/', 
            never_cache(
                ShownEditMaterial.as_view() 
            )
        ),
        path('tabs/show/edit/transaction/', 
            never_cache(
                ShownEditTransaction.as_view() 
            )
        ),
        path('tabs/show/edit/killed_transaction/', 
            never_cache(
                ShownEditKilledTransaction.as_view() 
            )
        ), 
        # tables with forms for new vals
        path('tabs/show/new/partner/', 
            never_cache(
                ShownNewPartner.as_view() 
            )
        ),
        path('tabs/show/new/material/', 
            never_cache(
                ShownNewMaterial.as_view() 
            )
        ),
        path('tabs/show/new/transaction/', 
            never_cache(
                ShownNewTransaction.as_view() 
            )
        ),
        # shown dropdowns(input lists)
        path('tabs/show/dropdown/partner/', 
            never_cache(
                ShownDropdownPartner.as_view() 
            )
        ),
        path('tabs/show/dropdown/partner_group/', 
            never_cache(
                ShownDropdownPartnerGroup.as_view() 
            )
        ),
        path('tabs/show/dropdown/employee/', 
            never_cache(
                ShownDropdownEmployee.as_view() 
            )
        ),
        path('tabs/show/dropdown/material/', 
            never_cache(
                ShownDropdownMaterial.as_view() 
            )
        ),
        path('tabs/show/dropdown/book_account/', 
            never_cache(
                ShownDropdownBookAccount.as_view() 
            )
        ),
        path('tabs/show/dropdown/deb_account/', 
            never_cache(
                ShownDropdownBookAccount.as_view() 
            )
        ),
        path('tabs/show/dropdown/cred_account/', 
            never_cache(
                ShownDropdownBookAccount.as_view() 
            )
        ),
        path('tabs/show/dropdown/hot_transaction/', 
            never_cache(
                ShownDropdownHotTransaction.as_view() 
            )
        ),
        path('tabs/show/dropdown_store/goodsline/', 
            never_cache(
                ShownDropdownStoreGoodsline.as_view() 
            )
        ),
        path('tabs/show/dropdown_stock/goodsline/', 
            never_cache(
                ShownDropdownStockGoodsline.as_view() 
            )
        ),
        # saved(sent to backend) data from 'edit' tables
        path('tabs/save/edit/partner/', 
            never_cache(
                SavedEditPartner.as_view() 
            )
        ),
        path('tabs/save/edit/material/', 
            never_cache(
                SavedEditMaterial.as_view() 
            )
        ),
        path('tabs/save/edit/transaction/', 
            never_cache(
                SavedEditTransaction.as_view() 
            )
        ),
        # saved data from 'new' tables
        path('tabs/save/new/partner/', 
            never_cache(
                SavedNewPartner.as_view() 
            )
        ),
        path('tabs/save/new/material/', 
            never_cache(
                SavedNewMaterial.as_view() 
            )
        ),
        path('tabs/save/new/transaction/', 
            never_cache(
                SavedNewTransaction.as_view() 
            )
        ),
        # killed(sent to backend to delete) data from 'edit' tables
        path('tabs/kill/edit/partner/', 
            never_cache(
                KilledEditPartner.as_view() 
            )
        ),
        path('tabs/kill/edit/material/', 
            never_cache(
                KilledEditMaterial.as_view() 
            )
        ),
        path('tabs/kill/edit/transaction/', 
            never_cache(
                KilledEditTransaction.as_view() 
            )
        ),
        path('tabs/kill/packet/transaction/', 
            never_cache(
                KilledPacketTransaction.as_view() 
            )
        ),
    ]

except:
    # when db is not init/models migrated yet
    urlpatterns = [
            path('', lambda *args: HttpResponse('')), 
    ]
